services:
  producer:
    image: kafka-producer:${BUILD_NUMBER}
    network_mode: host
    restart: on-failure

  consumer:
    image: kafka-consumer:${BUILD_NUMBER}
    network_mode: host
    restart: on-failure